### ISSUE TITLE
macro file not read

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#10]
nedit is using the macros defined in file $HOME/.neditmacro. But unfortunately, xnedit does not read this file automatically.

**Comment by unixwork** [comment]
XNEdit loads macros from $HOME/.xnedit/autoload.nm, so you can just move your .neditmacro file to this location and rename it accordingly.

NEdit 5.4 changed the paths of config files. Previously everything was stored directly in the home directory, but it was moved to $HOME/.nedit. In NEdit, the new path of the macro file is $HOME/.nedit/autoload.nm

NEdit still supports the older paths, however I removed the support of these legacy config files in the last XNEdit release.

**Comment by pucicu** [comment]
Hi,

thanks for this important information. Perhaps you can add this to the README.

I also appreciate your decision, because it allows me to test the original NEdit and XNEdit in parallel with different configurations.

Really great work! I’m happy that I found the modernized NEdit clone! ;-)

Best
Norbert
