### ISSUE TITLE
Status of these memory issues?

### ISSUE THREAD

**Issue by cblc** [unixwork/xnedit#103]
Having been a NEdit user for decades, I'm very excited to build and use XNedit!!! However, I found this discussion at the Sourceforge page, which worries me a bit, because for me NEdit has always been rock-solid, and never hit any memory bugs myself in all these years: https://sourceforge.net/p/xnedit/discussion/general/thread/4d1e469e6c/?limit=25#a5a2/16fc

I have not hit that bug yet, but any issues related to memory make me feel worried. Is there any progress in fixing those issues?

**Comment by unixwork** [comment]
The initial bug is fixed, the latest post describes a problem, that happens only with a weird unicode character and it doesn't crash XNEdit and is probably a bug in one of the libraries (I suspect Xft, fontconfig or something related).

In general, I had not many memory bugs, that would crash XNEdit, maybe 2 in actual stable releases. In my experience, stability is really not a problem.

**Comment by cblc** [comment]
Thank you very much! I built it, and it's running fine. I love the filechooser (reminds me of the SGI native file dialog, very nice), and the colorchooser too!
