### ISSUE TITLE
Possible bug: rectangular selections are offset to the left

### ISSUE THREAD

**Issue by cblc** [unixwork/xnedit#106]
I don't know if this is because I changed some resources, but when doing rectangular selections (dragging with the control key pressed), the rectangle is not at the cursor position, but offset to the left, as can be seen in this screen capture (you can see where the cursor is, and how the rectangle appeared to the left). Can you reproduce it? (if not, try to select a rectangle in the middle of the window rather than near of the left edge). Or is it only with my settings?
<img width="179" alt="Captura de Pantalla 2023-05-24 a las 23 48 18" src="https://github.com/unixwork/xnedit/assets/53348558/a6ff7e7a-b25f-438e-b196-2d6bb866f3ef">

**Comment by unixwork** [comment]
I wasn't able to reproduce this. Does this happen every time?

It could be a font specific problem. I could try it with the same OS and font settings.

**Comment by cblc** [comment]
You are right, the default font works fine. Try the font called "Courier", and you will see...

**Comment by cblc** [comment]
Btw, I'm using XQuartz 2.8.5 on MacOS Ventura, if it matters.

**Comment by unixwork** [comment]
Rectangular selections should work with the Courier font on macOS now (I think some other fonts were also affected)

**Comment by cblc** [comment]
Thank you very very much!! I'm building it right now...
