### ISSUE TITLE
UTF8 in menu entries

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#11]
I really appreciate the UTF8 in the edit window. Unfortunately, the menue entries are not yet UTF8 capable. Will this be changed in the future? I have some individual menue entries that use special characters.

**Comment by unixwork** [comment]
It is kind of possible already, however not really good.

If you are using an UTF8 locale, you can use UTF8 text in menu entries. However, motif only supports a single font for menu widgets when using Xft text rendering (which is used by default in XNEdit). Most fonts contain only a small amount of unicode characters. For full unicode support, Motif would need to switch to fallback fonts, which it doesn't do. I can't really change that.

A workaround would be to use a font that contains all unicode codepoints that you need. I know that there are some complete unicode fonts.

You can change the font of the menus and other ui elements with the following X resources:

nedit*defaultRT.fontName: <fontname>
nedit*fixedRT.fontName: <fontname>

I would like to improve this in the future, however this is a ton of work. I would need to reimplement at least some of Motifs widgets. This will not happen in the near future

**Comment by pucicu** [comment]
ok, I see. It has no high priority then.

**Comment by pucicu** [comment]
could you perhaps provide an example of how to use it via the X resources? I have tried with .Xdefaults but only `nedit*fontList:` works.

I have chosen a bold font for the menu: -*-helvetica-bold-r-normal-*-12-*-*-*-*-*-*-* (working quite well except for some special characters).

**Comment by unixwork** [comment]
It looks like your motif version doesn't support XFT text rendering. Don't know why. I will test it on macOS myself.

It is also possible to specify multiple fonts with fontList to support multiple charsets, but then you can only use bitmap fonts.

**Comment by unixwork** [comment]
I had success on macOS changing the font with the following X resources

nedit*defaultRT.fontName: <fontname>
nedit*fixedRT.fontName: <fontname>

The * was missing after nedit

Tested with openmotif from homebrew

Also, don't specify a X bitmap font, it supports truetype fonts. You can get a full list of installed fonts with the following command:

fc-list --format="%{family[0]}\n" | sort | uniq 

You still need a single font, that supports all characters that you need. Without knowing the special characters I can't help

**Comment by pucicu** [comment]
ah, I guess it should be 
`nedit*defaultRT.fontName:`
`nedit*fixedRT.fontName:`

because here Markdown is used, the `*`was interpreted to emphasize the string.

**Comment by pucicu** [comment]
I had alread the stars after nedit in `nedit*defaultRT.fontName:`. But I'm unsure how the fontname has to be specified. Could you please post an example? (with fontsize, boldface…)

**Comment by unixwork** [comment]
nedit*defaultRT.fontName: Papyrus
	nedit*defaultRT.fontSize: 12
	nedit*fixedRT.fontName: Papyrus
	nedit*fixedRT.fontSize: 12

terribly font, I know

**Comment by pucicu** [comment]
but helpful. thanks!

**Comment by pucicu** [comment]
sorry for my dumb question. but how can a set the font to be boldface here?

**Comment by unixwork** [comment]
Good question, I don't know if it is possible to set this with X resources.

Maybe it is possible programmatically

**Comment by unixwork** [comment]
Did you had success with a different font and are able to have special characters in menus?

**Comment by pucicu** [comment]
It is not yet really working. I am using now an UTF-8 enabled font, but some characters are missing (not all). Umlauts are there, and, thus, it is fine for now.
