### ISSUE TITLE
Makefile for macOS

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#12]
Because I'm working with macOS, I have used the FreeBSD makefile-Option. But I had to include the folders /opt/local/include (etc) because I have installed the dependencies via Macports. Perhaps you could also add such a Makefile-option? Would be nice (and is not much work).

**Comment by unixwork** [comment]
I already have a working macOS Makefile from an other user. I was just to lazy to add this to the repo yet.

**Comment by unixwork** [comment]
I've added a Makefile for macOS
