### ISSUE TITLE
Missing column sort arrow on second invocation of FSB in detail view

### ISSUE THREAD

**Issue by dpeterc** [unixwork/xnedit#122]
I use the fileselection box (FSB) in detail view.
On the first invocation, program correctly displays the default sort order by name, indicated by the top-down arrrow.
![xnedtiFSB1](https://github.com/unixwork/xnedit/assets/15419249/686d2db7-bc6c-4bbc-9037-be0f1ed3c9c1)
Then I click on the size button, and arrow moves and indicated the new sorting direction.
![xnedtiFSB2](https://github.com/unixwork/xnedit/assets/15419249/6b0f0f2a-a9cd-4045-b7a0-1cd19dd472b9)
If I then close the window, and reopen it, previous sort order is maintained (as it is correct), but the arrow button is not displayed.
![xnedtiFSB3](https://github.com/unixwork/xnedit/assets/15419249/43cc3681-cab3-439a-a373-4795ec186027)
This can be confusing to users, as there is no visual cue of the current 
sort order.

**Comment by unixwork** [comment]
The arrow is now always visible.

But I actually see another bug, when the FSB is opened again, the "Files" label is not really visible.

**Comment by dpeterc** [comment]
Indeed; that is quite strange as even a window resize does not fix that.
The second invocation of FSB in detail view can now look even worse, where part of the list is not redrawn properly as well.
![xnedtiFSB4](https://github.com/unixwork/xnedit/assets/15419249/b8bd9d2c-4db6-42a3-978b-e8efecd81da2)
This is fixed with window resize (or click on invisible columns).
But first impression is not actually worse on my computer. It looks like premature refresh, while geometry negotiations were not finished yet. Or one missing refresh at the end.

**Comment by unixwork** [comment]
I have disabled some changes from the last commit. Can you check if this fixes the redraw problem of the grid widget?

**Comment by dpeterc** [comment]
The redraw problem is fixed with your last commit, thank you very much.
The problem of missing label "Files" remains, but it is a minor issue.

**Comment by unixwork** [comment]
The label bug is also fixed now.

**Comment by dpeterc** [comment]
Tested and confirmed!
Thanks for being so responsive.
