### ISSUE TITLE
ANSI colors causes Segmentation fault      (core dumped) on Linux

### ISSUE THREAD

**Issue by rddunlap** [unixwork/xnedit#126]
Using xnedit 1.5.2 from github (cloned on 2023-OCT-20), I was editing fine until I used Default Preferences, clicked on ANSI Colors, saved defaults, and reloaded xnedit. xnedit shows nothing on screen. I just have  a message from Linux: Segmentation fault (core dumped). I am using Linux 6.5.4 on x86_64, openSUSE Tumbleweed environment.

**Comment by unixwork** [comment]
should be fixed now

**Comment by rddunlap** [comment]
Confirmed fixed. Thanks.
