### ISSUE TITLE
badly displayed font in active tab

### ISSUE THREAD

**Issue by sebqas** [unixwork/xnedit#128]
when I set the font by the X resource:

`nedit*fontList: -*-helvetica-medium-r-*-17-*-*-*-*-*-iso10646-1`

the filename in active tab is not properly displayed
![active-tab-2](https://github.com/unixwork/xnedit/assets/82983056/e4f83889-6bcd-4993-9de8-b487a285bc8d)
![active-tab-1](https://github.com/unixwork/xnedit/assets/82983056/7b6a86ac-f5d9-4301-be3d-8e865e996b34)
(with default setting is OK)
I have tried many other fonts but it looks the same

**Comment by unixwork** [comment]
You also have to specify a bold font, for example:

`nedit*fontList: -*-helvetica-medium-r-*-17-*-*-*-*-*-iso10646-1,-*-helvetica-bold-r-normal-*-17-*-*-*-*-*-iso8859-1=BOLD`

Alternatively, instead of using X11 bitmap fonts, you could also use truetype fonts:

	nedit*.renderTable: rt
	nedit*.renderTable.rt.fontName: Sans
	nedit*.renderTable.rt.fontSize: 10
	nedit*.renderTable.rt.fontType: FONT_IS_XFT

**Comment by sebqas** [comment]
> You also have to specify a bold font, for example:
> 
> `nedit*fontList: -*-helvetica-medium-r-*-17-*-*-*-*-*-iso10646-1,-*-helvetica-bold-r-normal-*-17-*-*-*-*-*-iso8859-1=BOLD`
> 
thanks, it works, but I need in the font with unicode, I have installed bold version of this font  

-*-helvetica-bold-r-*-*-17-*-*-*-*-*-iso10646-*

but cant use it here, why ?

> Alternatively, instead of using X11 bitmap fonts, you could also use truetype fonts:
> 
> ```
> nedit*.renderTable: rt
> nedit*.renderTable.rt.fontName: Sans
> nedit*.renderTable.rt.fontSize: 10
> nedit*.renderTable.rt.fontType: FONT_IS_XFT
> ```
 
that is much better, but how can I know that such resource was available ?
it is not listed in the xnedit Help menu

**Comment by unixwork** [comment]
Don't know why the bold `-*-helvetica-bold-r-*-*-17-*-*-*-*-*-iso10646-*` is not working. It is not really related to xnedit, this is more an X11 or motif issue.

And you are right, the XFT based render table config in xnedit is not documented. This is a actually a feature of the motif toolkit, but it would make sense to add this to the xnedit documentation.

**Comment by sebqas** [comment]
I don't  miss  bitmap fonts since I have truetypes  :)
 thanks, again
