### ISSUE TITLE
XIM Compose Sequences Fail To Work

### ISSUE THREAD

**Issue by roryyamm** [unixwork/xnedit#129]
Using the legacy XIM system (via the `uim-xim` bridge), trying to input compose sequences in XNedit does not work. Attempting to use the compose key simply outputs the characters in the sequence. This may be a duplicate of [a SourceForge issue](https://sourceforge.net/p/xnedit/bugs/28/), but that seems related to compose sequences in the context of macros. 

OS: Debian GNU/Linux trixie/sid x86_64
Version info:
```
XNEdit 1.5.2
Oct 5, 2023

     Built on: Linux, x86-64, GNU C
     Built at: Nov  7 2023, 22:23:52
   With Motif: (Untested) 2.3.8 [@(#)Motif Version 2.3.8]
Running Motif: 2.3 [unknown]
       Server: The X.Org Foundation 12101008
       Visual: 24-bit TrueColor (ID 0x21, Default)
       Locale: en_CA.UTF-8
```

Output of `setxkbmap`:

```
rules:      evdev
model:      sun_type6_usb
layout:     us
options:    lv3:ralt_switch,compose:menu,terminate:ctrl_alt_bksp
```

I'll try to reproduce the error with less esoteric hardware soon.

**Comment by unixwork** [comment]
Probably not a hardware problem, also I can test it with a sun type 7 keyboard.

Does compose work in other motif applications? And can you test it with this environment variable?

    export XMODIFIERS=@im=uim

**Comment by roryyamm** [comment]
…Ah. That seems to have solved it.

**Comment by Alex-Kent** [comment]
@unixwork Methinks this bug can be closed.  (Just to keep things tidy)
