### ISSUE TITLE
paste with middle mouse button (macOS)

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#13]
In the original NEdit I can paste with the middle mouse even from the primary clipboard (i.e. from the standard macOS clipboard). But with xnedit it is not possible. I can only paste what was selected in X11 applications. Would be nice (and important for me) to be able to paste from the macOS clipboard.

**Comment by unixwork** [comment]
I can reproduce this problem.

Pasting with the middle mouse button works in nedit but not in xnedit.

However it only works if the text is already in the macos clipboard. The real X11 primary selection doesn't work, even with nedit. And I don't think it can be implemented.

But I will fix the issue with pasting from the regular clipboard with the middle button.

**Comment by pucicu** [comment]
it can work, when you correctly set the “clipboard” properties of the X server (there is menue setting for the macOS’ Xorg). in macOS you select “update pasteboard when CLIPBOARD is changed” (or similar) and “activate synchronization"

**Comment by pucicu** [comment]
Would be really good to fix this bug (paste from macOS clipboard into XNedit). Thanks!

**Comment by unixwork** [comment]
Sorry for the delay. I'm really busy currently, but I will try to fix all the issues next week.

**Comment by unixwork** [comment]
should be fixed now

**Comment by pucicu** [comment]
Yes, great! Thanks!
