### ISSUE TITLE
Open File Dialog: Filter gets lost

### ISSUE THREAD

**Issue by MarkowEduard** [unixwork/xnedit#130]
Hi Olaf

Awesome work! I just found xnedit while desperately looking for a replacement for nedit with Unicode support. And moreover: I was very happy to find that building on FreeBSD 12.4 worked perfectly out of the box. I think about making a package. Many, many thanks!

One minor issue: setting a filter for file selection in the open dialog works perfectly, but when re-opening the file dialog the filter is gone. With the old nedit the filter is kept.

Kind regards

Eduard

**Comment by unixwork** [comment]
Hi,

thanks your for input. With the newest commit, the file dialog remembers the last filter string.

And a FreeBSD package would be awesome. Someone already created a package for NetBSD.

**Comment by MarkowEduard** [comment]
Awesome, and that fast, many thanks again. And I don't forget about the FreeBSD package!
