### ISSUE TITLE
Emojis not showing up in modal dialog

### ISSUE THREAD

**Issue by dpdoughe** [unixwork/xnedit#134]
Messages that contain emojis, such as what are emitted from the [Black](https://github.com/psf/black) code formatter after a successful run e.g., 
```
All done! ✨ 🍰 ✨
1 file left unchanged.
```
don't show up correctly in the modal output of xnedit.

![image](https://github.com/unixwork/xnedit/assets/23531138/30f36fb2-31a6-4223-a65c-eb13c3700390)

FYI, if it helps to test/verify I set up Black as a shell command in xnedit like so:

![image](https://github.com/unixwork/xnedit/assets/23531138/e7a03af1-3526-41b0-9f8f-8962d2e63a2d)

I've verified that the graphical emojis do show up correctly in Cygwin's Mintty at the terminal command line after following the procedure mentioned here:
https://github.com/mintty/mintty/wiki/Tips#installing-emoji-resources

however they do not show up in Xnedit's modal correctly. I'd be happy if even the unicode representation of those emojis were available in the modal. Any suggestions for what to try?

**Comment by unixwork** [comment]
This is a limitation in the Motif toolkit and unfortunately I don't think there is an easy solution.
