### ISSUE TITLE
Block selection (cntrl+select) region not rectangular or has offset 

### ISSUE THREAD

**Issue by dpdoughe** [unixwork/xnedit#135]
Cntrl+Select (block selection) is not working in Xnedit. There appear to be some strange offsets between the cursor and the dragged selection areas making the resulting selection region not appear rectangular.

![image](https://github.com/unixwork/xnedit/assets/23531138/a9aecd88-45f5-4821-91f4-8af56fd6b62d)

**Comment by unixwork** [comment]
It only works if you are using a monospaced font.

**Comment by dpdoughe** [comment]
Ah. It seems that maybe the fonts preferences are not getting saved to `~/.xnedit/nedit.rc` when edited through Preferences->Text Fonts... dialog

```
nedit.textFont: -adobe-courier-medium-r-normal--12-120-75-75-m-70-iso10646-1
nedit.boldHighlightFont: -adobe-courier-bold-r-normal--12-120-75-75-m-70-iso10646-1
nedit.italicHighlightFont: -adobe-courier-medium-o-normal--12-120-75-75-m-70-iso10646-1
nedit.boldItalicHighlightFont: -adobe-courier-bold-o-normal--12-120-75-75-m-70-iso10646-1
```
When I try to save Fira Code Retina, in my preferences (Save Defaults...) 

![image](https://github.com/unixwork/xnedit/assets/23531138/1aae881f-389f-4a56-a2a9-ef9eff043d8f)


the changes are not reflected in  `~/.xnedit/nedit.rc` even though I can use Fira font in Xnedit until I close the application. Upon reopening the application it reverts to adobe courier.

**Comment by unixwork** [comment]
How to you open the font settings? There is `Preferences -> Text Fonts...` and `Preferences -> Default Settings -> Text Fonts...`.

You have to go to the Default Settings sub menu and change settings there.

**Comment by dpdoughe** [comment]
Ah that was it!  Good now. Will close this issue. Thanks again!
