### ISSUE TITLE
UTF-8 support for input fields in dialogs

### ISSUE THREAD

**Issue by cblc** [unixwork/xnedit#139]
I just found that I cannot type international characters in the input fields of the Search, Replace, Open File, dialogs (and maybe in every input box, except for the editor).

In the text editor I can type whatever international character, and it works fine.

I don't know if using XQuartz and having customized some Motif resources could be the reason for this. If it works for you, tell me, because maybe it's my settings.

**Comment by unixwork** [comment]
If it works in the texteditor, you could add `-DXNE_TEXTFIELD` to the CFLAGS in your makefile and recompile xnedit. With this flag, xnedit is using an alternative textfield in the dialogs, that has better unicode support. It is not enabled by default yet, but that will change in the future.

Interestingly on macOS I can't enter non-ASCII characters directly, even in the text editor.

**Comment by cblc** [comment]
Ok, thanks!!,I will try building with `-DXNE_TEXTFIELD`. But, are you sure international characters don't work for you in the text editor on MacOS? I'm using a Mac and that works fine for me.

**Comment by unixwork** [comment]
Yes I'm sure. I haven't tried to fix this, yet.

**Comment by unixwork** [comment]
Is this problem solved?

**Comment by cblc** [comment]
Yes, it works by building with -DXNE_TEXTFIELD, @unixwork !!  I have one question, though: the new alternative textfield, the font that is used is smaller than the usual one. What resource do I need to adjust for getting back the usual font size? Kind regards, and thanks a lot!

**Comment by unixwork** [comment]
You can change the font with `*XmTextField.XftFont: Monospace:size=10`

Are you using an older version or the newest code? I enabled the new textfield by default (it can be disabled with `-DDISABLE_XNE_TEXTFIELD` and it should use the default Motif textfield font.

**Comment by cblc** [comment]
Thank you very much!! Yes, that's the resource, I changed the size to 12, which gives me a size similar to what I'm used to. And yes, I'm building with the latest code (I just downloaded today).

**Comment by cblc** [comment]
By the way, you are still using #ifdef XNE_TEXTFIELD in the code, look: https://github.com/unixwork/xnedit/blob/e57e28ae2b75016ebf5bbd50acf830b190f11121/source/nedit.c#L191

(Unless you are defining XNE_TEXTFIELD somewhere when DISABLE_XNE_TEXTFIELD is not defined)

**Comment by unixwork** [comment]
Yes, please open an issue for the encoding problem. I think this is an macOS related problem, because macOS stores file names in a specific normalized form of unicode, and it seems Motif has problems with that, but this is something that could be fixed.
