### ISSUE TITLE
copy from NEdit not in macOS clipboard

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#14]
perhaps related to the other issue: if I copy in xnedit using Cmd+C, the clipboard content should also be available in the macOS clipboard. At least this was the behaviour so far for classic NEdit. And it was really helpful feature to integrate the editor in the OS and to regularly use it.

**Comment by unixwork** [comment]
I can't reproduce this issue. I can copy with command+c in XNEdit. 

What doesn't work is pasting with command+v, however that doesn't work in nedit neither

I have tested it with macOS catalina with XQuartz. Openmotif was installed from homebrew. Are you using something different?

**Comment by pucicu** [comment]
have you copied with cmd+c in XNedit and pasted in some macOS app? this does not work for me. but pasting in another Xorg-app works.

i have installed the X libs using macports.

**Comment by unixwork** [comment]
Is this still an issue? I was able to accidential reproduce this problem, however it disappeared later. I think it has something to do with the XQuatz clipboard settings. Currently I have all checkboxes activated and it works.

**Comment by pucicu** [comment]
Seems to work now (after last update).
