### ISSUE TITLE
Line numbers are not updating when inserting a newline in a wrapped line

### ISSUE THREAD

**Issue by uap-universe** [unixwork/xnedit#142]
### Steps to reproduce

Enable "Continuous" wrap and enable line numbering.
In this example we use a window width of 80, but that does not matter.

Type the following line

    This is a test line that is longer than 80 characters which is used to demonstrate the issue.

Observe that the line is wrapped before the word "demonstrate".

Now place the caret immediately in front of the word "demonstrate" and press enter.

### Expected Behavior

The newline character is inserted and the line numbering is adjusted.

### Actual Behavior

The newline character is inserted but the line numbering is **not** adjusted.

However, any update to the window corrects the line numbering. For example, when you start scrolling, the line number gets immediately adjusted.

**Comment by unixwork** [comment]
Fixed
