### ISSUE TITLE
building on Cygwin

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#143]
hi,
you should list "libXt-devel" and "libXm-devel" as pre-requisite in "BUILDING XNEDIT" section for Cygwin in README.md
Something like:
...
- X11 development stuff (headers, libraries)
- libXt-devel and libXm-devel (cygwin)
- Xrender and Xft
- iconv (*BSD, cygwin)

...

**Comment by unixwork** [comment]
Motif is already mentioned in the requirements.

Does cygwin has a package manager? The readme also contains the exact install command for some platforms, it would be possible to add cygwin to this.

**Comment by efa** [comment]
the CLI command line is:
C:\Download\Cygwin>setup-x86_64.exe -qP <package list>

I will add the minimum packages list

**Comment by efa** [comment]
seem that <package list> ignore the package next to first, also with client 2.932.
So the installation command will be:
setup-x86_64.exe -qP gcc-g++ 
setup-x86_64.exe -qP make 
setup-x86_64.exe -qP git
setup-x86_64.exe -qP pkg-config 
setup-x86_64.exe -qP libX11-devel 
setup-x86_64.exe -qP libXt-devel 
setup-x86_64.exe -qP libXm-devel 
setup-x86_64.exe -qP libXrender-devel 
setup-x86_64.exe -qP libXft-devel 
setup-x86_64.exe -qP libiconv-devel 
setup-x86_64.exe -qP libfontconfig-devel 
setup-x86_64.exe -qP motif 
setup-x86_64.exe -qP bison

**Comment by efa** [comment]
found the packages must be coma separated, so work as so:
`setup-x86_64_2.932.exe -qP gcc-g++,make,git,pkg-config,libX11-devel,libXt-devel,libXm-devel,libXrender-devel,libXft-devel,libiconv-devel,libfontconfig-devel,motif,bison`

**Comment by unixwork** [comment]
I've added the command to the readme.
