### ISSUE TITLE
preferences : save defaults – not working

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#15]
sorry that I open so many issues.

already yesterday I noted that the "save defaults" button in the menue is not really working. at least all settings that I change via the preferences menue are not updated in the .xnedit/nedit.rc file. I had to add all my changes manually to this file.

**Comment by unixwork** [comment]
I noticed this problem yesterday after using special characters in a shell menu entry. With ascii only input it works. However I have problems to reproduce this issue.

Did you used special characters in a configuration?

**Comment by pucicu** [comment]
probably. when I open nedit.rc I get a warning that a number of "non-convertibe characters skipped – Open anyway?"
I'm not sure whether I can found all of them. They came by using the config file from the classic nedit.

**Comment by pucicu** [comment]
oh, now it s funny. I have changed some of them (they were visible as simply questionmarks) and now, after restart and opening again this the nedit.rc file, I have two questionsmarks at this place. the actual characters are gone again.

to illustrate where it comes from:
I have a macro that converts some umlauts to html code:

	Changecode>ger2html:::: {\n\
		ues[1]="ü"\n\
		ues[2]="ö"\n\
		ues[3]="ä"\n\
		ues[4]="ß"\n\
		ues[5]="Ü"\n\
		ues[6]="Ö"\n\
		ues[7]="Ä"\n\
		ues[8]="é"\n\
		ues[9]="ñ"\n\
		ues[10]=">"\n\
		ues[11]="<"\n\
		tex[1]="&uuml;"\n\
		tex[2]="&ouml;"\n\
		tex[3]="&auml;"\n\
		tex[4]="&szlig;"\n\
		tex[5]="&Uuml;"\n\
		tex[6]="&Ouml;"\n\
		tex[7]="&Auml;"\n\
		tex[8]="&eacute;"\n\
		tex[9]="&ntilde;"\n\
		tex[10]="&gt;"\n\
		tex[11]="&lt;"\n\
		\n\

**Comment by unixwork** [comment]
A potential problem that I didn't had on my radar. XNEdit is using UTF8 internally and old NEdit configuration files don't use UTF8.

Try to convert the old nedit.rc file to utf8 and it should work.

**Comment by pucicu** [comment]
actually I did already. but now I have another problem that I don’t understand: I cannot open files with utf8 umlauts. but I can type umlauts. when I save the file with umlauts, it says that it cannot the characters. I don’t know what has changes since yesterday when it was working.

**Comment by pucicu** [comment]
really strange, XNedit does not open anymore UTF8 files correctly.

**Comment by unixwork** [comment]
What if you specify UTF-8 as encoding in the open file dialog?

Also, what is content of your $LANG variable

If your locale is not a UTF-8 locale, the default encoding for loading files is not UTF-8

**Comment by pucicu** [comment]
aaaaah, ok, good hint!

today i have used xterm and was starting nedit from this shell. yesterday i used iterm. now it works.
