### ISSUE TITLE
First xnedit compilation, first core dumped.

### ISSUE THREAD

**Issue by ericxuo** [unixwork/xnedit#2]
Hi,

I've just compiled xnedit from the source code found on github.
make linux
After installing lesstif-devel package (I'm running Mageia 6), I could get the source/xnedit file.
./source/xnedit
Cannot get X Input Manager
Segmentation fault (core dumped)

xnedit opens without problem, I can navigate in the menus but each time I want to enter some text in the text area, xnedit immediately crashes with the above error message.

Any idea to solve the issue ?

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

On another PC (still using Mageia 6) and using Motif (if I believe xnedit) : 
XNEdit release of Jan 10, 2019

     Built on: Linux, x86-64, GNU C
     Built at: Jan 11 2019, 19:13:05
   With Motif: (Untested) 2.3.6 [@(#)Motif Version 2.3.6]
Running Motif: 2.3 [unknown]
       Server: Mageia 11905000
       Visual: 24-bit TrueColor (ID 0x21, Default)
       Locale: fr_FR.UTF-8

It is working fine. If you think it is better to use Motif, I can try recompiling with Motif instead of Lesstif on the 1st PC.
But I thought Lesstif was more "up-to-date" than Motif.

Regards.

Xuo.

**Comment by unixwork** [comment]
I fixed the crash when using lesstif.

There are still some bugs with lesstif but it works more or less.

The main reason for lesstif was that motif wasn't free software, but that has changed and motif is LGPL like lesstif now,
