### ISSUE TITLE
add C99 "bool" to syntax highlighting

### ISSUE THREAD

**Issue by dpeterc** [unixwork/xnedit#21]
C99 is 20 years old now and I believe widely used.
I use bool type (actually macro, but that is irrelevant in for this case), and syntax highlighting does not work in the same way as for int, char, float... which is annoying.
So I suggest to add bool in storage keyboard section of C language definition in highlightData.c
storage keyword:\"<(?:const|extern|auto|register|static|unsigned|signed|volatile|bool|char|double|float|int|long|short|void|typedef|struct|union|enum)>\":::Storage Type::D\n\

Or, if that would be annoying to other users, add an extra C99 language mode, with all the new keywords (bool, restrict, inline, complex, ...)

**Comment by efa** [comment]
paired with `true` and `false`

**Comment by unixwork** [comment]
xnedit 1.4.0 has updated C syntax highlighting
