### ISSUE TITLE
resizing window corrupts text in exposed window

### ISSUE THREAD

**Issue by netllama** [unixwork/xnedit#22]
If I resize the window, making it larger, the newly exposed text is always corrupted.  For example:

![corrupted](https://user-images.githubusercontent.com/71113/85586024-65ef0680-b5f5-11ea-8bbf-e02d522dcbfa.png)

If I force a window redraw event (minimize then restore the window, or highlight the text), the corruption is cleared.

I'm seeing this problem on a Linux system.

**Comment by dpeterc** [comment]
I can confirm this problem both on Linux and on MacOS.

**Comment by unixwork** [comment]
fixed
