### ISSUE TITLE
coredump when pressing ctrl +/- keys in help window

### ISSUE THREAD

**Issue by tksoh** [unixwork/xnedit#23]
Here's what happen I tried to zoom in/out in the help window on linux mint with openmotif 2.3.8:

	Program received signal SIGSEGV, Segmentation fault.
	0x00005555555b697e in SetZoom (window=0x0, step=1) at window.c:5399
	(gdb) where
	#0  0x00005555555b697e in SetZoom (window=0x0, step=1) at window.c:5399
	#1  0x0000555555607ada in zoom (w=0x555555d17e80, step=1) at text.c:3460
	#2  0x0000555555607b0a in zoomInAP (w=0x555555d17e80, event=0x7fffffffbe40, args=0x0, nArgs=0x7ffff7912270) at text.c:3464
	#3  0x00007ffff76f2a0d in ?? () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#4  0x00007ffff76f2e75 in ?? () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#5  0x00007ffff76f3b3d in _XtTranslateEvent () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#6  0x00007ffff76cbe52 in XtDispatchEventToWidget () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#7  0x00007ffff76cc83d in ?? () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#8  0x00007ffff76cc919 in XtDispatchEvent () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#9  0x00007ffff76d85cf in XtAppProcessEvent () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#10 0x00007ffff76ccd2d in XtAppMainLoop () from /usr/lib/x86_64-linux-gnu/libXt.so.6
	#11 0x00005555555924cb in main (argc=1, argv=0x7fffffffe108) at nedit.c:921
	(gdb) 

Ideally the help windows should support zooming too, but it's probably not worth the effort. I've attached a quick patch to 'stop the bleeding'. Feel free to ignore if you have some cleaner fix.

[xnedit-zoom-coredump-patch.txt](https://github.com/unixwork/xnedit/files/4841922/xnedit-zoom-coredump-patch.txt)

**Comment by unixwork** [comment]
implemented zoom in help window
