### ISSUE TITLE
File selection box in detail view does not accept shortcuts

### ISSUE THREAD

**Issue by dpeterc** [unixwork/xnedit#26]
In standard Motif file selection box, if you press a character, for example "k", scrolled list of files will automatically scroll to first position of the file starting with "k" and select it.
This does not work in detail view of file selection box.
For consistency (and also for fast access on large number of files), it would be better to have this feature as well.

**Comment by unixwork** [comment]
I agree. I'll try to add that soon.

**Comment by unixwork** [comment]
fixed

**Comment by dpeterc** [comment]
I can confirm that it works, but there are still two problems:
1) It should not beep as it selects the file starting by the pressed letter, as this is correct behavior. It should only beep if file starting by the pressed character does not exist.
2) On a long list, it should auto-scroll to the newly selected file. Otherwise the file is selected, but we do not know if it is the right one.

If these two things are fixed, then behavior will become equal to standard Motif file selection box in that respect.

**Comment by unixwork** [comment]
should be fixed now

**Comment by dpeterc** [comment]
Works as expected now, thank you.
