### ISSUE TITLE
Missing first 2 bytes when reloading modified file.

### ISSUE THREAD

**Issue by orionbelt** [unixwork/xnedit#29]
1. **echo '0123456789' > foo**
2. **xnedit foo &**                         // xnedit shows file contents correctly: 0123456789
3. **echo '0123456789' >> foo**   // add another line to foo
4. Move mouse cursor over xnedit window.
5. xnedit dialog pops up: "foo has been modified by another program. Reload?"  --> Select "Reload"
6. xnedit now displays the following two lines:
23456789
0123456789
The first 2 characters of the file ("01") are missing.
7. Modify file "foo" from inside xnedit and save.
8. **cat foo**: The saved file, too, misses the first 2 characters (i.e., it's not just a display issue).
9. In point 1 above, when **echo** writes a UTF string (e.g., **echo 'äbcdëf' > foo**), only the first character (ä) is missing, i.e. 2 bytes again.

XNEdit version 1.2.1

**Comment by unixwork** [comment]
Thanks for the detailed bug report.
