### ISSUE TITLE
Server Mode and xnc

### ISSUE THREAD

**Issue by jazzits** [unixwork/xnedit#32]
Hi, I read on the README file that it is recommended to run xnedit in server mode via xnc, but I couldn't find any documentation on how to do this. Could you point me somewhere or briefly describe how to go about this? Thanks.

**Comment by unixwork** [comment]
Hello,

The help menu contains a section about this topic (Help -> Client/Server Mode).

Basically, if you run xnc, it creates a new xnedit server, or it sends a command to an existing server. This is useful, if you want to open a file in an existing xnedit window. For example:

Run `xnc` the first time, which opens a new xnedit window.
Next, open a file with `xnc myfile.txt`, which opens a second tab in the already existing xnedit window.

**Comment by jazzits** [comment]
Thanks, I couldn't locate the Help menu because it's on the top right, unlike the other drop-down menus... silly me.
