### ISSUE TITLE
drag-and-drop only works once

### ISSUE THREAD

**Issue by dpeterc** [unixwork/xnedit#33]
Drag-and-drop works correctly the first time; the selected file gets opened, or if we already have an open file, it opens new window with that file.
But if you then select a different file and drop it again on the first xnedit window, nothing happens. This is because drag-and-drop is getting again the first file.
But if we drop it to another xnedit, it opens the correct newly selected file. It looks as if xnedit drag-and-drop would be locked by the first file dropped.
In my opinion, this is probably due to lack of calling XdndFinished, so drag and drop operation is not really complete, and the new one can not start.

**Comment by unixwork** [comment]
Indeed, the missing XdndFinished was the problem. It worked with some gtk file managers, but not with KDE.

Can you confirm, that the latest commit fixes the problem?

**Comment by dpeterc** [comment]
I confirm that it is working correctly now.
Thank you very much for the quick fix!
