### ISSUE TITLE
line numbers are corrupted in split pane view

### ISSUE THREAD

**Issue by netllama** [unixwork/xnedit#35]
I'm running an xnedit build (reported as 1.3.0) from May 20, 2021 on a Linux-x86_64 (Fedora 33) system.  I have line numbers enabled, and they work fine most of the time.  However, if I enable the split pane view, the line numbers end up blurred & corrupted when scrolling in all panes that are not the original/first pane in the view.  If I trigger a redraw event on the entire window (minimize, then maximize), the line numbers are fixed, until I scroll again.

**Comment by unixwork** [comment]
should be fixed now

**Comment by netllama** [comment]
Can confirm, its working well now.  Thanks for the super fast fix!
