### ISSUE TITLE
open dialog with wrong path

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#38]
just compiled git sources.
On both Debian/WSL and Cygwin I got wrong separation of path in open dialog, see attach.
Apparently .../c/xnedit/... is recognized as one directory istead of 'xnedit' inside 'c'.
The same happen for 'd/AMBIENTE' in Cygwin

![xnedit_dialog_debian](https://user-images.githubusercontent.com/1578980/119506377-259c8900-bd6e-11eb-8cda-a30527019dfd.png)
![xnedit_dialog_cygwin](https://user-images.githubusercontent.com/1578980/119506374-2503f280-bd6e-11eb-84e3-f8bc6dcb8126.png)

**Comment by unixwork** [comment]
The problem also existed on linux with folder names with just one character. Should work now.

**Comment by efa** [comment]
I can confirm it is fixed on both Debian/WSL and Cygwin
