### ISSUE TITLE
Initial Windows Size: strange window column number

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#39]
the number of column saved with "Preferences, Save Defaults" is not restored right,
while number of row is restored right.
I report below two settings and restored windows size:
menu Preferences, Default Settings, Initial Windows Size
```
52x52 => 52x149   ratio=2.865
52x28 => 52x 80   ratio=2.57
```
Seems related to orizontal windows resize resolution, I can change it by dragging on right edge, only by about 3 chars a time.
Happen on Cygwin only, but packaged nedit doesn't present this behaviour.
Any hints?

**Comment by efa** [comment]
maybe related to a missing font, see comparison with Nedit:
![xnedit_column_cygwin](https://user-images.githubusercontent.com/1578980/119649576-13c8ed80-be23-11eb-9186-345a095f4388.png)

**Comment by unixwork** [comment]
Seems like it isn't a monospace font. If I use Sans as a font on linux, I have a similar behavior.

**Comment by efa** [comment]
I kept commented the 'nedit.rc' lines:
nedit.textFont: ...
nedit.boldHighlightFont: ...
nedit.italicHighlightFont: ...
nedit.boldItalicHighlightFont: ...
Is there a log to look at?
What other can be?

**Comment by efa** [comment]
I can confirm courier is rendered with a proportional font, see attach:
![xnedit_column_cygwin_font](https://user-images.githubusercontent.com/1578980/119692562-cb71f580-be4b-11eb-921a-1a41294b7e0a.png)

This is the list of installed, font related, packages:
```
dejavu-fonts          2.37-1
font-tektronix-misc   2.6-5
fontconfig            2.13.1-2
ghostscript-fonts-other 6.0-1
libXfont1             1.5.4-1
libXfont2_2           2.0.4-1
libfontconfig-common  2.13.1-2
libfontconfig-devel   2.13.1-2
libfontconfig1        2.13.1-2
libfontenc1           1.1.4-1
mkfontscale           1.2.1-1
texlive-collection-fontsrecommended 20210325-1
texlive-collection-fontutil 20210325-1
urw-base35-fonts      20170801-5
xorg-x11-fonts-Type1  7.5-4
xorg-x11-fonts-dpi100 7.5-4
xorg-x11-fonts-dpi75  7.5-4
xorg-x11-fonts-misc   7.5-4
```
Something missing?

**Comment by unixwork** [comment]
Can you check in the Font Selector (Preferences -> Text Fonts -> Browse) if you have DejaVu Sans Mono? If it isn't there, try another font.

**Comment by efa** [comment]
I found something promising:
xnedit (in Cygwin) load/save preference from/to:
~/.nedit/.nedit.rc
instead of:
~/.xnedit/.nedit.rc

So I commented the 4 fonts lines in ~/.xnedit as per readme instructions, but Xnedit do not read that.
Once commented the 4 fonts in ~/.nedit/.nedit.rc, xnedit started to use a monospace font and correctly restore column number.

**Comment by efa** [comment]
DejaVu Sans Mono is there

**Comment by unixwork** [comment]
I'm confused, it should not load anything from ~/.nedit/.nedit.rc

The xnedit config file is ~/.xnedit/nedit.rc

**Comment by efa** [comment]
The save path is confirmed also by the dialog box that open once clicked menu Preferences, Save Defaults...
This happen on Xnedit Cygwin binary only, on Debian I got the right behave for Xnedit.
Nedit work well in both Cygwin and Debian

**Comment by efa** [comment]
here the Save Defaults Preferences dialog where you can see the used path is ~/.nedit:
![xnedit_column_cygwin_config](https://user-images.githubusercontent.com/1578980/119803364-af1f9880-bedf-11eb-97ed-e661db6cf5d1.png)

**Comment by unixwork** [comment]
An older version of nedit stored config in the file ~/.nedit and later they switched it to ~/.nedit/nedit.rc

Nedit still supports loading from the legacy config file. I thought that I have removed this, but actually no. So, if .nedit exists (as a file, not as a directory), xnedit loads settings from it. 

This is definitely a bug and not a feature, therefore I removed support for the legacy .nedit file now.

**Comment by efa** [comment]
sorry, I didn't make myself clear.
The file that is updated is ~/.nedit/nedit.rc and not ~/.nedit (I was speaking about the directory).
I do not have .nedit file in my home

**Comment by unixwork** [comment]
In util/utils.c the function GetRCFileName(NEDIT_RC) will deliver the path to the config file.

Do you have the environment variable NEDIT_HOME set? Before my last commit, if this variable was set, config is loaded from $NEDIT_HOME/nedit.rc. I changed the name to XNEDIT_HOME now.

**Comment by efa** [comment]
yes I have:
NEDIT_HOME=/cygdrive/c/Users/vmessina.MI-CGS/.nedit

**Comment by efa** [comment]
work very well now.
Will try to generate a Cygwin package

**Comment by efa** [comment]
and to have Unicode AND Nedit is great! BRAVO
