### ISSUE TITLE
Is it possible to have the full path of the file in the statistic line ?

### ISSUE THREAD

**Issue by ericxuo** [unixwork/xnedit#4]
Hi,

The full path of the file is not displayed in the statistic line.
In the example below, I expect to see /home/eric/README
![screenshot_20190113_102023](https://user-images.githubusercontent.com/9089499/51083593-390aa480-171d-11e9-9d86-49a937c290d4.png)

Is it possible to have the full path name of the file to be displayed ?

regards.

xuo.

**Comment by unixwork** [comment]
I can't reproduce this. Normally it should show the full path. Does this always happen for you?

I would need step by step instructions to reproduce this.

**Comment by ericxuo** [comment]
Hi,

Yes it happens on all files I open with xnedit. I've copy/paste some lines of .nedit/nedit.rc into .xnedit/nedit.rc. But I've renamed the .xnedit directory and it still appears. I'll see if I've got the same issue on another pc. But this feature is 100% mandatory for me.

Regards.

Xuo.

**Comment by unixwork** [comment]
Found the problem. It was actually a feature for the SGI version of nedit, and one user wanted to have this SGI setting for linux and made a pull request. I looked at it and thought it only adds some features, but it actually changes some things like the statistic line.

It is now deactivated by default and when you recompile the newest version, the statistic line shows the full path.
