### ISSUE TITLE
tabbed editing: drag and drop of a tab

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#41]
can be useful the possibility to re-order the tabs in a multi-tabbed editor.
I think Motif does not have this native widgets possibility, but may be implemented anyway in a modern editor

**Comment by unixwork** [comment]
This was already requested by some users and is on my roadmap. It will be one of the next features I implement, however it can take a while, until I start adding new features.

**Comment by efa** [comment]
this just to keep track on the RFE

**Comment by unixwork** [comment]
It is now possible to reorder tabs with drag and drop. It only works inside of one window, so it is not possible to drag a tab to another window. Also there is no visual indication yet.

**Comment by efa** [comment]
wow, I will try immediately

**Comment by efa** [comment]
on Debian work

**Comment by efa** [comment]
I can confirm work well on Cygwin 64 and 32-bit too

**Comment by efa** [comment]
thank you
