### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#44]
please add 'X11 pixmap library' to list of dependencies

On Debian I had to do:
sudo apt install libx11-dev libxrender-dev libxft-dev libfontconfig1-dev libmotif-dev libpcre3-dev bison libxpm-dev

**Comment by efa** [comment]
libiconv-dev is another dependencies not listed in the documentation

**Comment by unixwork** [comment]
I've added Xpm and iconv to the dependencies.

Also, the Xpm dependency will be removed in the future and libiconv is only required on some platforms.
