### ISSUE TITLE
Cannot get X Input Manager

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#51]
I got the subject message on each run of XNEdit on Debian.
Anyway input of non-ASCII character work.

$ xnedit -V
XNEdit 1.3.3
Aug 18, 2021

     Built on: Linux, x86-64, GNU C
     Built at: Aug 19 2021, 15:04:53
   With Motif: (Untested) 2.3.8 [@(#)Motif Version 2.3.8]
Running Motif: 2.3 [unknown]
       Server: The X.Org Foundation 12004000
       Visual: 24-bit TrueColor (ID 0x51, Default)
       Locale: it_IT.UTF-8

Distro: LMDE 4 (debbie) debbie
based on Debian 10 Buster 6 July 2019

$ uname -a
Linux 08i7-2500 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

pkg: xorg
version: 1:7.7+19
ver: X11R7.7+19 X.Org X Server 1.20.4

pkg: libmotif-dev
version: 2.3.8-2

**Comment by efa** [comment]
just made a test, without checking for NULL returned by XmImGetXIM(), and always executing next calls, work as before, I cannot find differences. Non-ASCII input char work.

text.c:
```
/*
** Widget realize method
*/
static void realize(Widget w, XtValueMask *valueMask,
	XSetWindowAttributes *attributes)
{    
    /* Set bit gravity window attribute.  This saves a full blank and redraw
       on window resizing */
    *valueMask |= CWBitGravity;
    attributes->bit_gravity = NorthWestGravity;
        
    /* Continue with realize method from superclass */
    (xmPrimitiveClassRec.core_class.realize)(w, valueMask, attributes);

 /* create X input context */
    TextWidget text = (TextWidget)w;
    text->text.xim = XmImGetXIM(w);
    /*if(!text->text.xim) {
        TextPrintXIMError();
    } else {*/
        Window win = XtWindow(w);
        XIMStyle style = XIMPreeditNothing | XIMStatusNothing;
        text->text.xic = XCreateIC(
                text->text.xim,
                XNInputStyle,
                style,
                XNClientWindow,
                win, 
                XNFocusWindow,
                win,
                NULL);
    //}
    
    TextDInitXft(text->text.textD);
    
    XdndEnable(w);
}
```

**Comment by unixwork** [comment]
Yes, when there is no XIM it still works, because I'm using a fallback in that case. Bigger desktops like Gnome, KDE or Xfce usually have an Input Method like Ibus, which is a requirement, if you want to type something like Chinese characters.

I guess I can just remove the error message to not annoy users that don't have an input method.

**Comment by efa** [comment]
my current Windows manager is MATE (Gnome 2)

**Comment by efa** [comment]
I made a try and installed ibus, the selected Chinese-Wubi, and work, I can input Chinese characters using my keyboard both in a text editor and the terminal. Running XNEdit (selecting from the bash history) I got always the same message

**Comment by unixwork** [comment]
I need to set the XMODIFIERES environment variable to use ibus in xnedit:

`XMODIFIERS=@im=ibus`

Btw, I have removed the error message now

**Comment by efa** [comment]
I made a try with the variable defined as so, but I got always the message, also when Chinese input is selected and the terminal write in Chinese

**Comment by efa** [comment]
no it is OK
