### ISSUE TITLE
Edit|Lower-case and Edit|Upper-case do not work on non-ASCII characters

### ISSUE THREAD

**Issue by lersek** [unixwork/xnedit#54]
* Symptom experienced with xnedit 1.3.3:

The `Edit|Lower-case` / `Edit|Upper-case` functions turn non-ASCII characters into garbage. Each such character is then displayed as two question marks inside rectangular frames, on my end anyway.

* Superficial analysis of the source code at commit e6c8b55:

The `Edit|Lower-case` and `Edit|Upper-case` logic is implemented in the `changeCase()` function, file `source/shift.c`. This function calls `toupper()` and `tolower()`, which do not work on multi-byte characters.

* Superficial idea for a solution:

My understanding is that xnedit's internal text buffers carry UTF-8 (not `wchar_t`). If that's correct, then it's somewhat unfortunate in this regard, because UTF-8 cannot be passed to `towupper()` / `towlower()`.

One idea would be set up up a conversion from `"UTF-8"` to `"WCHAR_T"` with `iconv_open()`, and then to pass the `wchar_t` objects produced by `iconv()` to `towupper()`. Unfortunately, `towupper()` has a nasty requirement: unless it's passed `WEOF`, its `wint_t` argument must be such a `wchar_t` value that corresponds to a *valid codepoint in the current locale*.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/towupper.html

In other words, if `iconv()` translated a UTF-8 sequence to `wchar_t` successfully, but the resultant `wchar_t` value were not covered by the current locale, then `towupper()` would be toast!

Therefore, the translation to `wchar_t` should happen with `mbrtowc()`, not `iconv()`. `mbrtowc()` is itself locale-aware. `mbrtowc()` will report such `wchar_t` codepoints *early* that are not covered by the locale (and would therefore be undefined for `towupper()`).

https://pubs.opengroup.org/onlinepubs/9699919799/functions/mbrtowc.html

Finally, after `towupper()` returns, the `wchar_t` should be translated back to UTF-8 -- and the number of octets in that sequence need not necessarily equal the number of octets in the original UTF-8 sequence. In other words, case conversion could even shorten or lengthen the text buffer, as expressed in octets.

Thanks!

**Comment by unixwork** [comment]
I thank you for the very detailed description. I fixed it in the way you suggested it. It should work now.

Do you have an example for characters that have different numbers of octets, depending on lower/upper case?

**Comment by lersek** [comment]
> I thank you for the very detailed description. I fixed it in the way you suggested it. It should work now.

Thanks!

I've checked at commit 9066b1d. Case conversion works in UTF-8-encoded locales (such as in `LC_CTYPE=hu_HU.UTF-8`). It does not work in non-UTF-8-encoded locales (such as `LC_CTYPE=hu_HU.ISO8859-2`). However, given the existent limitations with non-UTF-8 locales (such as "only ASCII input" in Search/Replace, at least without `-DXNE_TEXTFIELD`), I'll stick with `LC_CTYPE=hu_HU.UTF-8` anyway. So my issue has been solved, based on my brief testing. Thank you.

> Do you have an example for characters that have different numbers of octets, depending on lower/upper case?

I believe a common example is:

https://en.wikipedia.org/wiki/Dotted_and_dotless_I#In_computing

In the `POSIX` locale for example, the correspondence is between `I` (U+0049) and `i` (U+0069); each is encoded with a single byte in UTF-8.

But in a Turkish locale, one correspondence is between `I` (U+0049) and `ı` (U+0131), and another is between `İ` (U+0130) and `i` (U+0069). In the first case, lower-casing lengthens the UTF-8 sequence (from `0x49` to `0xC4 0xB1`); while in the last case, lower-casing shortens the UTF-8 sequence (from `0xC4 0xB0` to `0x69`).

**Comment by unixwork** [comment]
> It does not work in non-UTF-8-encoded locales (such as `LC_CTYPE=hu_HU.ISO8859-2`).

I actually tried to make it work with every locale. If a non-UTF-8 locale is used, I temporarily switch to C.UTF-8. It seems C.UTF-8 isn't available on all systems. I guess I have to adjust just the encoding part of the locale.
