### ISSUE TITLE
regression when saving a file at a non-relative pathname

### ISSUE THREAD

**Issue by lersek** [unixwork/xnedit#57]
In NEdit-5.7, the following test case works:

```
mkdir /tmp/1
cd /tmp/1
nedit
# insert a new line into the empty text buffer
# press Ctrl-S
# in the New File Name field, type "/tmp/x.txt", and press Enter.
```

The new file is saved at `/tmp/x.txt`, regardless of the current working directory being `/tmp/1`.

In xnedit at commit 9066b1d3, the test case fails (invoking `xnedit` in place of `nedit` of course).

The primary symptom is that a *No such file or directory* error message pops up. The failure happens regardless of whether `-DMOTIF_FILEDIALOG` was specified in `CFLAGS` (e.g. in `makefiles/Makefile.linux`). I reproduced this symptom with both builds.

Presumably, xnedit does not recognize that the new file's pathname is an absolute one, not a relative one, and so the save attempt is made with `/tmp/1/tmp/x.txt`. Because no directory `/tmp/1/tmp` exists, the error is reported.

The secondary symptom is that, if *further* attempts are made to save the file, xnedit sometimes segfaults. This secondary symptom is specific to `-DMOTIF_FILEDIALOG` being absent, AFAICT.

**Comment by unixwork** [comment]
Fixed it in the new file dialog, however if any parent in the specified path doesn't exist, it still fails.

Interestingly absolut pathnames in nedit don't work on my system.

**Comment by lersek** [comment]
Tested at commit d7218af7761e (without `-DMOTIF_FILEDIALOG`); works well. Thank you!

**Comment by lersek** [comment]
> if any parent in the specified path doesn't exist, it still fails

That's OK -- the file save dialog is not expected to transparently create missing directories. It's really only about re-enabling the same behavior that the original NEdit file save dialog provided. Frequently, I need to save a new file like `hello.txt` under an absolute pathname prefix like `/foo/bar/baz`  -- all existent directories -- , and then cutting&pasting `/foo/bar/baz` from an open terminal window into the file save dialog is very convenient. Thanks!
