### ISSUE TITLE
background of line numbers is different/ does not change

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#59]
Hello,
in the pevious version, the column with the line numbers had the same background colour as the rest of the editor pane. But now it is different and I could not find any setting that allows me to change the line number column. The problem is that I use a specific background colour and now this column looks quite strange, because the (obviously default) gray background of this column does not fit.
Thanks for any help to find this setting or to implement one!
Norbert

**Comment by unixwork** [comment]
There is a new setting in the Colors dialog:

```
Preferences -> Default Settings -> Colors...

Line Numbers Background
```

Hope that helps.

**Comment by pucicu** [comment]
very cool! good job! thank you very much!
