### ISSUE TITLE
show coordinate list of non-convertible characters

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#61]
when there automatic detection of encoding fail, appear the message:
3 non-convertible characters skipped
it would be very useful know the coordinate L: y C: x
maybe in a dialog box

**Comment by unixwork** [comment]
I added a dropdown menu, that contains all skipped characters. It doesn't show coordinates (yet), but you can click on an entry and the character is selected.

There is probably room for improvements, but it should be helpful.
