### ISSUE TITLE
Error on FreeBSD 12 when forwarded to another display

### ISSUE THREAD

**Issue by emuman100** [unixwork/xnedit#62]
Hello,

I was able to compile XNEdit 1.1.3 on my FreeBSD 12.0 system. I run applications by forwarding them to my Mac using XQuartz to display them. When I run XNedit, the following message displays in my terminal:

Cannot get X Input Manager

When I go to open a file, the program closes and prints this message in the terminal:

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  69 (X_FillPoly)
  Resource id in failed request:  0x0
  Serial number of failed request:  8878
  Current serial number in output stream:  9102

The same happens when I try to Save As. When I go to Open Selected, I get the error that pops up on the X display. Image attached. 
![Screen Shot 2021-09-06 at 2 54 41 PM](https://user-images.githubusercontent.com/64179229/132254125-a29d70d6-1856-482d-9cbd-d4ca9c44cd1f.png)

Thank you.

**Comment by unixwork** [comment]
Do you mean XNEdit 1.3.1? There is no version 1.1.3, and 1.1.* is also quite old.

**Comment by emuman100** [comment]
Sorry, this is 1.3.3.

**Comment by unixwork** [comment]
I was not able to reproduce this yet. I have tested it with FreeBSD 13 and macOS 10.15. I will also try FreeBSD 12.

Can you please try the following:

1. Start xnedit (remote on FreeBSD)
2. in a second ssh session, get the pid of the xnedit process
3. run as root (replace pid): `dtrace -n 'syscall::exit:entry /execname == "xnedit"/ { ustack(); }' -p <pid>`
4. in xnedit, go to *File -> Open* or what ever triggers the problem
5. post the dtrace output

**Comment by unixwork** [comment]
Another thing that you could try:

1. On macOS, run `echo "nedit*newFolder.labelType: XmSTRING" | xrdb -merge -`
2. run xnedit on FreeBSD and try *File -> Open*

**Comment by emuman100** [comment]
Hi,

Here is the dtrace output:

dtrace -n 'syscall::exit:entry /execname == "xnedit"/ { ustack(); }' -p 65860
dtrace: description 'syscall::exit:entry ' matched 2 probes
dtrace: pid 65860 exited with status 1
CPU     ID                    FUNCTION:NAME
  1  61940                       exit:entry
              libc.so.7`_exit+0xa
              libX11.so.6.3.0`_XDefaultWireError
              libX11.so.6.3.0`_XError+0x158
              libX11.so.6.3.0`0x80087cb6f
              libX11.so.6.3.0`_XEventsQueued+0x5d
              libX11.so.6.3.0`XCheckIfEvent+0x89
              libXm.so.2.0.1`0x8006f500e
              libXt.so.6.0.0`_XtMakeGeometryRequest+0x375
              libXt.so.6.0.0`XtMakeGeometryRequest+0x134
              libXm.so.2.0.1`0x8006f470a
              libXt.so.6.0.0`_XtMakeGeometryRequest+0x375
              libXt.so.6.0.0`XtMakeGeometryRequest+0x134
              libXm.so.2.0.1`_XmGeoArrangeBoxes+0x66f
              libXm.so.2.0.1`XmFontListEntryLoad+0xd0
              libXt.so.6.0.0`XtRealizeWidget+0xac
              libXm.so.2.0.1`_LtDebugWidgetGeometry2String+0x10e
              libXt.so.6.0.0`ManageChildren+0x239
              libXt.so.6.0.0`XtManageChildren+0xd0
              libXt.so.6.0.0`XtManageChild+0x1a
              xnedit`ManageDialogCenteredOnPointer+0x8c

For your second post, nothing printed.

Thanks.

Jonathan

**Comment by emuman100** [comment]
I believe I know what the problem might be. I installed nedit and it installed openmotif. After recompiling xnedit, everything works.

Before I installed nedit, I had installed lesstif, and that's what xnedit was using. It looks like that during compilation, it uses openmotif even if lesstif is installed.

**Comment by unixwork** [comment]
Good to know that it works now. XNEdit doesn't run well with lesstif, I have seen other problems with it.
