### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#67]
Hi,

I have sometimes (actually quite often) the problem that when I scroll within the NEdit window, the text rendering becomes very slow and I can see that it is appearing letter by letter. This is then preventing the scrolling until the complete text is rendered. After this, the scrolling is continued. Sometimes it seems to be related whether I have not yet saved the text modifications. After saving it, the scrolling is fast. But sometimes it also appears in non-modified text.

I use it with XQuartz 2.8.1 in macOS 11.6.1. Motif version is 2.3.8 (I think it is the one from macports).

Any idea where this comes from and how to improve this behaviour?

Best
Norbert

**Comment by unixwork** [comment]
Hi,

the main problem is that XQuartz has very poor performance, especially with Motif applications. I think Xorg from macports doesn't have this bug and should work much better.

**Comment by dpeterc** [comment]
XQuartz behaves badly with X11 applications which do a lot of calls which require round trip (reply from a function, before it can continue with execution of next one).
Drawing of text labels in Motif with XFT (antialiased fonts) queries background color for each label, and this causes the slowdown on XQuartz.  It was working OK on MacOS versions before El Capitan.
There is a fix for Motif library that mostly solves this problem (the part of Motif slow drawing text with XFT).
http://bugs.motifzone.com/show_bug.cgi?id=1715
You can compile motif from source and apply the patch from the link above.
There is also a pre-compiled patched version of Motif for Mac, which you can download from here. You will need to replace the library by yourself.
http://www.winteracter.com/motif.htm

Xorg from macports is not better than XQuartz at the moment, since XQuartz has been updated this year in order to support M1 processors.

**Comment by pucicu** [comment]
Thanks for the explanation. Unfortunately, this information is not enough that I can fix this problem myself. The winteracter lib is a ".a" static library, but xnedit is linked against a ".dylab" library. How can I use the ".a" lib instead? The other way, to compile motif from scratch, is also not possible because I have no idea in which file I have to apply this patch.

Now, as I see that there would be a solution, I really would like to solve this problem. Thanks for any help!

**Comment by dpeterc** [comment]
The library.a is for static linking, so unless you build xnedit by yourself and know how to modify the makefiles, you can not do it.
If you wanted to apply the patch, you would have to edit XmRenderT.c, which is located in lib/libXm of the Motif source.

But the Winteractor site also contains the patched Motif .dylib for MacOS 64 bits Intel processors, but only in the full Motif package
http://www.winteracter.com/openmotif/openmotif-2_3_8_patched.osx13.x86_64.tar.gz
the library is located in
motif-2.3.8/lib/Xm/.libs/libXm4.dylib

**Comment by unixwork** [comment]
The patched Motif library improves performance in dialogs and menus, but not in xnedit's main text widget. If Xorg from macports is not a solution, I don't know what would help.

I have not seen this scrolling related issue on macOS, maybe I can improve the rendering performance, however I don't have a quick solution.

In general I think the user experience on macOS is not good. I hope to improve it in the future, however I'm waiting for Apple to release a new desktop mac.

**Comment by dpeterc** [comment]
Can you make a video which demonstrates slow scrolling in xnedit?

If the fix in the Motif library does not help, then xnedit itself needs to be analyzed for excessive use of round trip Xlib calls.
Basically one would need to do
grep XQuery *.c
grep XGet *.c
and observe suspected positions in code which might be called many times.
Sometimes simply a printf() with counter of this function calls helps in discovering the problem.
If such a point is found, then it has to be checked, if it is possible to avoid some of these calls by caching or smarter algorithms.

**Comment by pucicu** [comment]
I have now installed Xorg using macports. It seems to solve the scrolling problem. I will test it in the next week more intensively.

Thanks for the useful comments!

**Comment by pucicu** [comment]
I have to correct me. The problem is still existing. It is strange that I had no problems yesterday evening. I was quite happy that the editor worked well, even for very long data files. But now, the problem is back (with another file).

**Comment by pucicu** [comment]
Attached a screen recording of the scrolling issue:

https://user-images.githubusercontent.com/972432/140660846-e4403178-65ac-4cae-8a5b-b685e13614b9.mp4
