### ISSUE TITLE
Add support for DESTDIR in Makefile

### ISSUE THREAD

**Issue by drmpjz** [unixwork/xnedit#69]
In the last step of building an RPM, the resulting files of a project are installed into a temporary buildroot from where the rpmbuild utility collects them for packaging into the RPM archive.

This is commonly supported in Makefiles using the DESTDIR variable, but this is missing in xnedit. If DESTDIR is not set, there is no change in the behaviour of the make file.

The following patch implements the requested change.
--- Makefile.orig       2021-12-28 17:09:32.171693956 +0100
+++ Makefile    2021-12-28 17:09:11.227741948 +0100
@@ -57,15 +57,15 @@
 #
 INSTALL_FILES=source/xnedit source/xnc
 install: $(INSTALL_FILES)
-       mkdir -p $(PREFIX)/bin
-       mkdir -p $(PREFIX)/share/icons
-       mkdir -p $(PREFIX)/share/applications
-       rm -f $(PREFIX)/bin/xnedit
-       rm -f $(PREFIX)/bin/xnc
-       cp source/xnedit $(PREFIX)/bin/xnedit
-       cp source/xnc $(PREFIX)/bin/xnc
-       cp resources/desktop/xnedit.png $(PREFIX)/share/icons/xnedit.png
-       sed s:%PREFIX%:$(PREFIX):g resources/desktop/xnedit.desktop.template > $(PREFIX)/share/applications/xnedit.desktop
+       mkdir -p $(DESTDIR)$(PREFIX)/bin
+       mkdir -p $(DESTDIR)$(PREFIX)/share/icons
+       mkdir -p $(DESTDIR)$(PREFIX)/share/applications
+       rm -f $(DESTDIR)$(PREFIX)/bin/xnedit
+       rm -f $(DESTDIR)$(PREFIX)/bin/xnc
+       cp source/xnedit $(DESTDIR)$(PREFIX)/bin/xnedit
+       cp source/xnc $(DESTDIR)$(PREFIX)/bin/xnc
+       cp resources/desktop/xnedit.png $(DESTDIR)$(PREFIX)/share/icons/xnedit.png
+       sed s:%PREFIX%:$(PREFIX):g resources/desktop/xnedit.desktop.template > $(DESTDIR)$(PREFIX)/share/applications/xnedit.desktop
 
 #
 # The following is for creating binary packages of NEdit.

P.S. You've heard it before, but I am one of the long time users too, and very happy that xnedit is under active delvelopment again :-)

**Comment by unixwork** [comment]
Hi and thanks for your input. I have applied your changes and make install now supports DESTDIR.
