### ISSUE TITLE
Foreground selection color ignored?

### ISSUE THREAD

**Issue by tanabi** [unixwork/xnedit#7]
Hey there;

When I go into Preferences > Default Settings > Colors...

I configure my colors how I want them, however it looks like the "Selection Foreground" color is ignored no matter what I set it to.  It always uses the "Plain Text Foreground" for the selected text.  I have syntax highlighting turned off if that matters.  This works fine in regular nedit.

Selection Background does work correctly.

**Comment by unixwork** [comment]
Hi,

thanks for the bug report. Not only selection foreground was ignored, also matching foreground was not used.

Both should work now.

Regards

**Comment by tanabi** [comment]
This is confirmed fixed on my end.  Thanks for your work, and thanks for helping to continue nedit into the future :)
