### ISSUE TITLE
RFE: Case Sensitive Find Selection

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#74]
as now CTRL+H and Shift+CTRL+H do Case Insensitive Find Selection forward and backward.
Often I want to do Case Sensitive Find Selection, please RFE.
Seems the only free shortcut are: [Shift]+CTRL+B and CTRL+U?

**Comment by unixwork** [comment]
You can set the search style to case sensitive (Preferences ->  Default Settings -> Searching -> Default Search Style). Are separate menu entries really required?

**Comment by efa** [comment]
work. I didn't knew the settings work on Find Selection too, I think was for search dialog only.
Thanks, I'm OK with this
