### ISSUE TITLE
Font selector displays unordered fonts list 

### ISSUE THREAD

**Issue by kungbore68** [unixwork/xnedit#8]
Hi,
when I open the font selector window, it shows the fonts list completely (or apparently?) unordered.

![xnedit](https://user-images.githubusercontent.com/53895485/62686201-82c22180-b9c4-11e9-9d74-a326d2f3a15a.png)

Regards,
Marco

**Comment by unixwork** [comment]
Hi,

Yes, currently there is no sorting implemented for fonts. I put this on my todo list.

Also it would be good to have filters to show only fixed width fonts.

regards

**Comment by kungbore68** [comment]
Hi,I agree with you.
Regards

    Il giovedì 8 agosto 2019, 13:53:38 CEST, unixwork <notifications@github.com> ha scritto:  
 
 
Hi,

Yes, currently there is no sorting implemented for fonts. I put this on my todo list.

Also it would be good to have filters to show only fixed width fonts.

regards

**Comment by unixwork** [comment]
Hi,

I fixed this issue. The font list is now sorted.
