### ISSUE TITLE
glibc detected - free(): invalid pointer: with indent rainbow feature

### ISSUE THREAD

**Issue by patricevenant** [unixwork/xnedit#83]
Hi
I'm running xnedit on RedHat and I got this error. I just launch xnedit and activate the "indent rainbow" feature, on next mouse event/keyboard event I got the next error. I ran under gdb to have more information if needed :

XNEdit 1.4.0
Jan 9, 2022

     Built on: Linux, x86-64, GNU C
     Built at: Feb  4 2022, 22:59:02
   With Motif: 2.3.3 [@(#)Motif Version 2.3.3]
Running Motif: 2.3 [unknown]
       Server: The X.Org Foundation 60900000
       Visual: 24-bit TrueColor (ID 0x23, Default)
       Locale: en_US.UTF-8

0 ✓ :~/.../xnedit-1.4.0/xnedit$>gdb source/xnedit 
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from $HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit...done.
(gdb) run
Starting program: $HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit 
*** glibc detected *** $HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit: free(): invalid pointer: 0x0000000000b75630 ***
======= Backtrace: =========
/lib64/libc.so.6[0x32eca75dee]
/lib64/libc.so.6[0x32eca78c3d]
/usr/lib64/libfontconfig.so.1[0x32f1619c38]
/usr/lib64/libfontconfig.so.1(FcPatternDestroy+0x7f)[0x32f1619eff]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x462f4c]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x462fcf]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x4664df]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x467340]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x467855]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x46951b]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x46a220]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x46be62]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x465e7d]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x45d5b2]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x45f22e]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x45f9c3]
/usr/lib64/libXt.so.6[0x3300c4a59d]
/usr/lib64/libXt.so.6[0x3300c4a9d9]
/usr/lib64/libXt.so.6(_XtTranslateEvent+0x5c5)[0x3300c4afd5]
/usr/lib64/libXt.so.6(XtDispatchEventToWidget+0x3fb)[0x3300c21dab]
/usr/lib64/libXt.so.6[0x3300c225db]
/usr/lib64/libXt.so.6(XtDispatchEvent+0xb4)[0x3300c21614]
/usr/lib64/libXt.so.6(XtAppProcessEvent+0x269)[0x3300c2ebf9]
/usr/lib64/libXt.so.6(XtAppMainLoop+0x2d)[0x3300c20f8d]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x40c71c]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x32eca1ed1d]
$HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit[0x40afb9]
======= Memory map: ========
00400000-00553000 r-xp 00000000 00:1e 304998056                          $HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit
00752000-00773000 rw-p 00152000 00:1e 304998056                          $HOME/Projects/NEdit/xnedit-1.4.0/xnedit/source/xnedit
00773000-00b77000 rw-p 00000000 00:00 0                                  [heap]
32ec600000-32ec620000 r-xp 00000000 fd:00 2097575                        /lib64/ld-2.12.so
32ec820000-32ec821000 r--p 00020000 fd:00 2097575                        /lib64/ld-2.12.so
32ec821000-32ec822000 rw-p 00021000 fd:00 2097575                        /lib64/ld-2.12.so
32ec822000-32ec823000 rw-p 00000000 00:00 0 
32eca00000-32ecb8a000 r-xp 00000000 fd:00 2098953                        /lib64/libc-2.12.so
32ecb8a000-32ecd8a000 ---p 0018a000 fd:00 2098953                        /lib64/libc-2.12.so
32ecd8a000-32ecd8e000 r--p 0018a000 fd:00 2098953                        /lib64/libc-2.12.so
32ecd8e000-32ecd90000 rw-p 0018e000 fd:00 2098953                        /lib64/libc-2.12.so
32ecd90000-32ecd94000 rw-p 00000000 00:00 0 
32ece00000-32ece02000 r-xp 00000000 fd:00 2099006                        /lib64/libdl-2.12.so
32ece02000-32ed002000 ---p 00002000 fd:00 2099006                        /lib64/libdl-2.12.so
32ed002000-32ed003000 r--p 00002000 fd:00 2099006                        /lib64/libdl-2.12.so
32ed003000-32ed004000 rw-p 00003000 fd:00 2099006                        /lib64/libdl-2.12.so
32ed200000-32ed208000 r-xp 00000000 fd:00 2896697                        /usr/lib64/libXp.so.6.2.0
32ed208000-32ed407000 ---p 00008000 fd:00 2896697                        /usr/lib64/libXp.so.6.2.0
32ed407000-32ed408000 rw-p 00007000 fd:00 2896697                        /usr/lib64/libXp.so.6.2.0
32ed600000-32ed683000 r-xp 00000000 fd:00 2098979                        /lib64/libm-2.12.so
32ed683000-32ed882000 ---p 00083000 fd:00 2098979                        /lib64/libm-2.12.so
32ed882000-32ed883000 r--p 00082000 fd:00 2098979                        /lib64/libm-2.12.so
32ed883000-32ed884000 rw-p 00083000 fd:00 2098979                        /lib64/libm-2.12.so
32eda00000-32eda15000 r-xp 00000000 fd:00 2098984                        /lib64/libz.so.1.2.3
32eda15000-32edc14000 ---p 00015000 fd:00 2098984                        /lib64/libz.so.1.2.3
32edc14000-32edc15000 r--p 00014000 fd:00 2098984                        /lib64/libz.so.1.2.3
32edc15000-32edc16000 rw-p 00015000 fd:00 2098984                        /lib64/libz.so.1.2.3
32ede00000-32ee0a2000 r-xp 00000000 fd:00 2926172                        /usr/lib64/libXm.so.4.0.3
32ee0a2000-32ee2a2000 ---p 002a2000 fd:00 2926172                        /usr/lib64/libXm.so.4.0.3
32ee2a2000-32ee2cc000 rw-p 002a2000 fd:00 2926172                        /usr/lib64/libXm.so.4.0.3
32ee2cc000-32ee2cd000 rw-p 00000000 00:00 0 
32ef600000-32ef624000 r-xp 00000000 fd:00 2925870                        /usr/lib64/libxcb.so.1.1.0
32ef624000-32ef824000 ---p 00024000 fd:00 2925870                        /usr/lib64/libxcb.so.1.1.0
32ef824000-32ef825000 rw-p 00024000 fd:00 2925870                        /usr/lib64/libxcb.so.1.1.0
32efa00000-32efa02000 r-xp 00000000 fd:00 2888280                        /usr/lib64/libXau.so.6.0.0
32efa02000-32efc02000 ---p 00002000 fd:00 2888280                        /usr/lib64/libXau.so.6.0.0
32efc02000-32efc03000 rw-p 00002000 fd:00 2888280                        /usr/lib64/libXau.so.6.0.0
32efe00000-32eff37000 r-xp 00000000 fd:00 2925871                        /usr/lib64/libX11.so.6.3.0
32eff37000-32f0137000 ---p 00137000 fd:00 2925871                        /usr/lib64/libX11.so.6.3.0
32f0137000-32f013d000 rw-p 00137000 fd:00 2925871                        /usr/lib64/libX11.so.6.3.0
32f0200000-32f0211000 r-xp 00000000 fd:00 2925872                        /usr/lib64/libXext.so.6.4.0
32f0211000-32f0411000 ---p 00011000 fd:00 2925872                        /usr/lib64/libXext.so.6.4.0
32f0411000-32f0412000 rw-p 00011000 fd:00 2925872                        /usr/lib64/libXext.so.6.4.0
32f0600000-32f0626000 r-xp 00000000 fd:00 2099003                        /lib64/libexpat.so.1.5.2
32f0626000-32f0825000 ---p 00026000 fd:00 2099003                        /lib64/libexpat.so.1.5.2
32f0825000-32f0828000 rw-p 00025000 fd:00 2099003                        /lib64/libexpat.so.1.5.2
32f0a00000-32f0a98000 r-xp 00000000 fd:00 2925862                        /usr/lib64/libfreetype.so.6.3.22
Program received signal SIGABRT, Aborted.
0x00000032eca32495 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install expat-2.0.1-13.el6_8.x86_64 fontconfig-2.8.0-5.el6.x86_64 freetype-2.3.11-17.el6.x86_64 glibc-2.12-1.212.el6.x86_64 libICE-1.0.6-1.el6.x86_64 libSM-1.2.1-2.el6.x86_64 libX11-1.6.4-3.el6.x86_64 libXau-1.0.6-4.el6.x86_64 libXcursor-1.1.14-2.1.el6.x86_64 libXext-1.3.3-1.el6.x86_64 libXfixes-5.0.3-1.el6.x86_64 libXft-2.3.2-1.el6.x86_64 libXmu-1.1.1-2.el6.x86_64 libXp-1.0.2-2.1.el6.x86_64 libXpm-3.5.10-2.el6.x86_64 libXrender-0.9.10-1.el6.x86_64 libXt-1.1.4-6.1.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libpng-1.2.49-2.el6_7.x86_64 libuuid-2.17.2-12.28.el6_9.2.x86_64 libxcb-1.12-4.el6.x86_64 openmotif-2.3.3-9.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) info stack
#0  0x00000032eca32495 in raise () from /lib64/libc.so.6
#1  0x00000032eca33c75 in abort () from /lib64/libc.so.6
#2  0x00000032eca703a7 in __libc_message () from /lib64/libc.so.6
#3  0x00000032eca75dee in malloc_printerr () from /lib64/libc.so.6
#4  0x00000032eca78c3d in _int_free () from /lib64/libc.so.6
#5  0x00000032f1619c38 in ?? () from /usr/lib64/libfontconfig.so.1
#6  0x00000032f1619eff in FcPatternDestroy () from /usr/lib64/libfontconfig.so.1
#7  0x0000000000462f4c in FontListAddFontForChar (f=0x987fd0, c=10900240) at textDisp.c:4688
#8  0x0000000000462fcf in FindFont (f=0x987fd0, c=10900240) at textDisp.c:4741
#9  0x00000000004664df in drawString (textD=0xa93670, style=0, rbIndex=<value optimized out>, x=46, y=5, fromX=46, toX=46, string=0x7fffffff9c70, nChars=0, highlightLine=1 '\001', 
    ansi=0x7fffffff9c30) at textDisp.c:2547
#10 0x0000000000467340 in redisplayLine (textD=0xa93670, visLineNum=0, leftClip=46, rightClip=766, leftCharIndex=46, rightCharIndex=2147483647) at textDisp.c:2333
#11 0x0000000000467855 in textDRedisplayRange (textD=0xa93670, start=<value optimized out>, end=<value optimized out>) at textDisp.c:814
#12 0x000000000046951b in bufModifiedCB (pos=0, nInserted=4, nDeleted=0, nRestyled=0, deletedText=0x0, cbArg=0xa93670) at textDisp.c:1886
#13 0x000000000046a220 in callModifyCBs (buf=0xb39f50, pos=0, nDeleted=0, nInserted=4, nRestyled=0, deletedText=0x0) at textBuf.c:2381
#14 0x000000000046be62 in BufInsert (buf=0xb39f50, pos=0, text=0xb6cc80 "    ") at textBuf.c:520
#15 0x0000000000465e7d in TextDInsert (textD=<value optimized out>, text=<value optimized out>) at textDisp.c:1012
#16 0x000000000045d5b2 in simpleInsertAtCursor (w=0xa93210, chars=0xb6cc80 "    ", event=0x7fffffffb750, allowPendingDelete=<value optimized out>) at text.c:3700
#17 0x000000000045f22e in TextInsertAtCursor (w=0xa93210, chars=0xb6cc80 "    ", event=0x7fffffffb750, allowPendingDelete=1, allowWrap=1) at text.c:1594
#18 0x000000000045f9c3 in processTabAP (w=0xa93210, event=0x7fffffffb750, args=<value optimized out>, nArgs=<value optimized out>) at text.c:2563
#19 0x0000003300c4a59d in ?? () from /usr/lib64/libXt.so.6
#20 0x0000003300c4a9d9 in ?? () from /usr/lib64/libXt.so.6
#21 0x0000003300c4afd5 in _XtTranslateEvent () from /usr/lib64/libXt.so.6
#22 0x0000003300c21dab in XtDispatchEventToWidget () from /usr/lib64/libXt.so.6
#23 0x0000003300c225db in ?? () from /usr/lib64/libXt.so.6
#24 0x0000003300c21614 in XtDispatchEvent () from /usr/lib64/libXt.so.6
#25 0x0000003300c2ebf9 in XtAppProcessEvent () from /usr/lib64/libXt.so.6
#26 0x0000003300c20f8d in XtAppMainLoop () from /usr/lib64/libXt.so.6
#27 0x000000000040c71c in main (argc=1, argv=<value optimized out>) at nedit.c:928
(gdb)

**Comment by patricevenant** [comment]
Yes, thanks

Another issue is during the vertical selection with another Monospace font. The selected text isn't the one under the mouse/cursor. Do you have that ?
Thanks

**Comment by eteran** [comment]
@unixwork out of curiosity, what the heck is the "indent rainbow" feature? Is that a new adition to xnedit?

I also do have a minor concern about your fix for this. You did this:

```
if(toX < fromX || nChars == 0) return;
```

Which, sure, makes sense. Avoids the problem. But..

That implicitly makes this code never happen just a few lines down:

```
if(nChars == 0) rbIndex = -1;
```

So, either the second line is now useless, or the first line is prevent a legitimate code path from being taken. Just wanted to bring it to your attention :-)

**Comment by unixwork** [comment]
@eteran Yes, it is a new xnedit feature. If it is enabled, tabs/spaces until the first non-white character are drawn with a background color and each indentation level has a different color. 

@patricevenant Can you describe the problem in more detail? Which font are you using and can you provide a test file, in which  the problem occurs?

**Comment by patricevenant** [comment]
It's a quite strange, the Fira-Font gives me this trouble on Ubuntu 20.04. On RedHat, the Fira-Font has the correct behavior. I can play with the vertical selection without any issue. On Ubuntu, after Fira-Font, I can select the Fantasque-Font per example and the trouble disappers. I suspect an error in the Fira-Font file.
