### ISSUE TITLE
xnc opens files in new windows instead of tabs 

### ISSUE THREAD

**Issue by nglass** [unixwork/xnedit#87]
Hi,

I'm remotely logged into a number of CentOS servers using mobaxterm X11 on windows. xnc is opening files in new windows instead of tabs.

Debugging the server process, server.c:isLocatedOnDesktop is returning False because QueryDesktop is returning -1.
Patching the function to also return True for windowDesktop == -1 has the desired effect, however I don't know how "correct" that is. There is already a check against 0xffffffff for "sticky" windows.  On 32-bit that would have been -1...

PS - thanks for keeping nedit alive.

Regards

Nick

XNEdit 1.4.0
Jan 9, 2022

Built on: Linux, x86-64, GNU C
Built at: Apr  7 2022, 22:22:47
With Motif: 2.3.4 [@(#)Motif Version 2.3.4]
Running Motif: 2.3 [unknown]
Server: Moba/X 12101003
Visual: 24-bit TrueColor (ID 0x21, Default)

Locale: en_US.UTF-8

**Comment by nglass** [comment]
I hadn't spotted that querydesktop was in util/  and that I was using a default build with optimisations on so gdb was skipping stuff.   I'll try again later and dig in a little further to follow the code.

**Comment by nglass** [comment]
Looks like it's only an issue when using the MobaX Xorg version in mobaxterm.  Switching to the Cygwin X server and xnc plays nicely.

With cygwinX at this point
            if (isLocatedOnDesktop(window, currentDesktop) || !window->opened) {
                return window;
            }
isLocatedOnDesktop has returned False.  !window->opened is True so we return window.
With MobaX isLocatedOnDesktop is also False.  However !window->opened is now False, so it opens a new one.

TBH neither seems entirely correct, but at least the cygwin version behaves as I'd like so I'll stick with that for now.

I suspect isLocatedOnDesktop should be finding the window, however:
On cygwinX QueryDesktop doesn't find _NET_WM_DESKTOP.
On mobaX is does, but then queryDesktop gets an actualType of None.  QueryCurrentDesktop fares better.

**Comment by unixwork** [comment]
I have also tested VcXsrv and xnc works there as expected. It looks like with mobaxterm the root window has a desktop but the application window does not.

I think adding `if (windowDesktop == -1) return True;` is ok and shouldn't break anything on normal linux desktops.
