### ISSUE TITLE
.desktop file does not work

### ISSUE THREAD

**Issue by JamesOlvertone** [unixwork/xnedit#88]
The desktopfile with xnc entry does not start any xnedit window.
OS: Xubuntu 21.10

`[Desktop Entry]
Version=1.0
Name=XNEdit
GenericName=XNEdit
Comment=Nirvana Text Editor
Exec=/mypath/xnc -tabbed %F
TryExec=/mypath/bin/xnc
Categories=Application;Utility;TextEditor;
Icon=xnedit
Terminal=false
MimeType=text/plain;
Type=Application
Keywords=Text;Editor;Plaintext;Write;
Actions=new-window;new-document;

[Desktop Action new-window]
Name=New Window
Name[en_GB]=New Window
Exec=/mypath/bin/xnc -untabbed

[Desktop Action new-document]
Name=New Document
Name[en_GB]=New Document
Exec=/mypath/bin/xnc -tabbed
`
When I change all the "xnc" to "xnedit" it works.
/mypath/bin  is added to $PATH and exported.
When I open a shell and enter xnedit xnedit starts. When I enter xnc, xnedit starts.

**Comment by unixwork** [comment]
Is the path correct in this line?

**Comment by JamesOlvertone** [comment]
Yes. When I enter /mypath/xnc -tabbed foofilename.txt in a terminal xnedit is started.

**Comment by JamesOlvertone** [comment]
It semiworks with this (found this in eclipse.desktop):

Put this
#!/usr/bin/env xdg-open
on the first line in the .desktop and make xnedit.desktop executable xnedit starts up as expected with the xnc line.
Starting it from the whisker-menue/application-menue does not work, xnedit entry is visible in the menue.
