### ISSUE TITLE
Xm.h is missing

### ISSUE THREAD

**Issue by JamesOlvertone** [unixwork/xnedit#89]
Add some description in Readme which packages you need for compilation.

If someone gets the error
#include <Xm/Xm.h> not found.

You need the add the .deb-package libmotif-dev for compilation under Ubuntu (or any other linux).

Theres no configure script that gives you hints whats missing, so add some notes whats needed.

Thank you.

**Comment by efa** [comment]
the Readme section BUILDING XNEDIT:
https://github.com/unixwork/xnedit#building-xnedit
report
`Motif 2.0 or above`
as a prerequisite.
Every distro (deb, rpm, pacman, ...) has that in a different package name, so you have to guess the exact name from a search
