### ISSUE TITLE
line spacing is too high

### ISSUE THREAD

**Issue by daveriesz** [unixwork/xnedit#93]
I'm coming to XNedit after using old Nedit for something like 25 years.  For the longest time, I've been using the font:

    -adobe-courier-medium-r-normal--14-100-100-100-m-90-iso8859-1

The best analog I can seem to find in XNedit is:

    Courier:size=11

The font size seems to match pretty well, but the line spacing looks to be about 50% greater.  Is it possible to allow this to be adjusted?

**Comment by unixwork** [comment]
The line spacing depends on the font. It is actually possible to use old bitmap fonts like adobe courier in xnedit, and it looks just like nedit.

Manually adjusting the line spacing is currently not possible. Reducing it could lead to some rendering bugs, and you could probably save only one pixel.

For example, try to measure the space between these two lines in xnedit with your font:

    g  
    Â

In my case, there is only one white pixel between the two lines.

**Comment by daveriesz** [comment]
Screenshot from (classic) NEdit:
![ga-nedit](https://user-images.githubusercontent.com/7664602/218804898-3d6d8b5e-f99b-4f53-a180-e9b6263eff06.png) line spacing is 1 pixel, total height is 21 pixels

Screenshot from XNEdit:
![ga-xnedit](https://user-images.githubusercontent.com/7664602/218804900-6e55f6e2-2015-4d76-b0bd-3360b4843af6.png) line spacing is 4 pixels, total height is 25 pixels

Is it possible to specify the font in such a way that the font renderer will reduce the line spacing?  Something like:

```Courier:size=11:vpadding:1```

I can't find any doc describing this sort of specification string, so I'm not even sure if I'm thinking about it correctly.

**Comment by daveriesz** [comment]
Another item to note:

I'm using Ubuntu with the packages `xfonts-100dpi` and `xfonts-75dpi` installed.  I can use the bitmap Courier font from these packages as you described in XNEdit.

However to do this I must remove the package "texlive-fonts-recommended" because XNEdit's font selector cannot distinguish between the "Courier" fonts in these packages.

**Comment by unixwork** [comment]
The font name in XNEdit is passed directly to Xft/Fontconfig. There is no attribute to change the line height.

You can check which exact font is used with the tool fc-match, for example `fc-match Courier`



In your screenshot the line spacing is quite high. I'm using DejaVu Sans Mono, and it has much less empty space.

![DejaVu Sans Mono](https://user-images.githubusercontent.com/44745050/219009322-a48a7ea8-512c-45ad-bc4c-2d1b705abd02.png)

**Comment by daveriesz** [comment]
Thanks for taking the time to explain this to me.  It's clear that this isn't a defect in XNEdit.  I'll close the issue.
