### ISSUE TITLE
remove sorting in open/save dialog 

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#96]
can you add the remove of sort in open/save dialog?
Once the down/up arrow is shown, is not possible to back to unsorted list, neither selecting "List" and then again "Detail".
You can also do a three click loop: up, down, unsorted on column header

**Comment by dpeterc** [comment]
In my xnedit, the file and directory list in FSB is always sorted alphabetically by default.
What would be the purpose of unsorted list? Visual exercise in pattern matching?
In my opinion, it would be an unnecessary complication.

**Comment by efa** [comment]
OK, you are right that is an unnecesary cosmetic only feature. Priority 0 :-)
Think at about the 'ls -l' command, it show file in the file system order by default, and only using sort options, order them per data, name and so on.

**Comment by unixwork** [comment]
I don't see any benefit of unsorted files lists. The downside is that no other GUI file browser does this and we would deviate from standard behavior that the user expects. Also the memory footprint would be higher, because I would need an additional copy of the data.
