### ISSUE TITLE
incorrect behavior in multi-desktop environemnt

### ISSUE THREAD

**Issue by daveriesz** [unixwork/xnedit#97]
I'm using a number of multi-desktop (not multi-monitor) XFCE systems.  With (the original) NEdit, a new window opens for each desktop from which it is invoked, creating a tab in that window for each file opened from that desktop.  With XNEdit, the application window is moved from one desktop to the next.

To reproduce:

1. Start on Desktop 1 and open a file.  An XNEdit application window will be created containing that file.
2. Move to Desktop 2 and open a different file.  The XNEdit application window will me moved from Desktop 1 to Desktop 2 and will contain tabs for both open files.

The correct behavior should be for each desktop to contain a separate application window with only the file(s) opened from that desktop.

**Comment by unixwork** [comment]
It should work as expected now.

**Comment by daveriesz** [comment]
Much better, thanks!
