### ISSUE TITLE
RFE: Initial Window size: set to current

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#99]
please add a "set to current" Button, to the dialog box of Initial Window Size settings:
![XNEdit_winSize](https://user-images.githubusercontent.com/1578980/234337576-e24a7463-16dd-4626-94c1-bac8305b174a.png)

**Comment by efa** [comment]
can be also a new line below Custom... in menù:
![XNEdit_winSize2](https://user-images.githubusercontent.com/1578980/234339835-d8265823-c15f-44c2-a2af-645cd24b833b.png)

**Comment by unixwork** [comment]
Good idea. Another solution would be to just have the current window size as default values in the "Initial Window Size" dialog.

**Comment by unixwork** [comment]
With the latest commit, the "Initial Window Size" dialog has the current size as default values. This should solve this issue.

**Comment by efa** [comment]
well, work here, thank you
